

-include Makefile.targets


all: ${TARGETS} Makefile.targets

.SUFFIXES: .mp4 .mvtxt

.mp4.mvtxt:
	nice -19 python doge_catcher.py $< > $@

SRC=

Makefile.targets:
	python gen_lists.py ${SRC}

debug.mp4: input.mp4
	ffmpeg -flags2 +export_mvs -i input.mp4 -vf codecview=mv=pf+bf+bb $@
